### PR TITLE
fix: Make provider-argocd Application controller report accurate Ready state

### LINKED ISSUE #239: Application resources report sycned and ready regardless of underlying Application resource status
### What happened?
provider-argocd Application managed resources report Synced and Ready status to Crossplane regardless of the state of the underlying Application

### How can we reproduce it?
Deploy an Application via Crossplane using the provider-argocd provider.

### What environment did it happen in?
Crossplane version:  1.18
Crossplane Provider argocd version: latest

### PR DESCRIPTION
**Pull request by jwitko**
### Description of your changes

Fixes #239 

I have:

- [X] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.  # this doesn't exist?

### How has this code been tested
* Unit tests added for new ready check function
* Code functionally validated locally:

Resource added but not synced
```
$ kubectl get application.applications.argocd.crossplane.io/example-application -o yaml
apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-02-13T00:35:15-05:00"
    crossplane.io/external-create-succeeded: "2025-02-13T00:35:15-05:00"
    crossplane.io/external-name: example-application
  creationTimestamp: "2025-02-13T05:35:15Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 1
  name: example-application
  resourceVersion: "20927991"
  uid: ee652706-032a-46aa-af12-239f64cc252f
spec:
  deletionPolicy: Delete
  forProvider:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: charts/podinfo
      repoURL: https://github.com/stefanprodan/podinfo/
      targetRevision: HEAD
  managementPolicies:
  - '*'
  providerConfigRef:
    name: argocd-provider
status:
  atProvider:
    health:
      message: ""
      status: Missing
    resources:
    - group: ""
      health:
        message: ""
        status: Missing
      hook: false
      kind: Service
      name: example-application-podinfo
      namespace: default
      requiresPruning: false
      status: OutOfSync
      syncWave: 0
      version: v1
    - group: apps
      health:
        message: ""
        status: Missing
      hook: false
      kind: Deployment
      name: example-application-podinfo
      namespace: default
      requiresPruning: false
      status: OutOfSync
      syncWave: 0
      version: v1
    sourceType: Helm
    summary: {}
    sync:
      comparedTo:
        destination:
          name: ""
          namespace: default
          server: https://kubernetes.default.svc
        source:
          chart: ""
          path: charts/podinfo
          ref: ""
          repoURL: https://github.com/stefanprodan/podinfo/
          targetRevision: HEAD
      revision: b99bf8c252d47db1cccfb6546aec650679645e61
      status: OutOfSync
  conditions:
  - lastTransitionTime: "2025-02-13T05:35:16Z"
    message: 'Health status: Missing; Sync status: OutOfSync'
    reason: Unavailable
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-02-13T05:35:15Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

After resource synced:
```
apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-02-13T00:35:15-05:00"
    crossplane.io/external-create-succeeded: "2025-02-13T00:35:15-05:00"
    crossplane.io/external-name: example-application
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"applications.argocd.crossplane.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"example-application"},"spec":{"forProvider":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"charts/podinfo","repoURL":"https://github.com/stefanprodan/podinfo/","targetRevision":"HEAD"}},"providerConfigRef":{"name":"argocd-provider"}}}
  creationTimestamp: "2025-02-13T05:35:15Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 1
  name: example-application
  resourceVersion: "20928324"
  uid: ee652706-032a-46aa-af12-239f64cc252f
spec:
  deletionPolicy: Delete
  forProvider:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: charts/podinfo
      repoURL: https://github.com/stefanprodan/podinfo/
      targetRevision: HEAD
  managementPolicies:
  - '*'
  providerConfigRef:
    name: argocd-provider
status:
  atProvider:
    health:
      message: ""
      status: Healthy
    history:
    - id: 0
      revision: b99bf8c252d47db1cccfb6546aec650679645e61
      source:
        chart: ""
        path: charts/podinfo
        ref: ""
        repoURL: https://github.com/stefanprodan/podinfo/
        targetRevision: HEAD
    operationState:
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: false
          username: admin
        retry:
          limit: 0
        sync:
          dryRun: false
          prune: false
          revision: b99bf8c252d47db1cccfb6546aec650679645e61
          syncStrategy:
            hook:
              force: false
      phase: Succeeded
      retryCount: 0
      syncResult:
        resources:
        - group: ""
          hookPhase: Running
          hookType: ""
          kind: Service
          message: service/example-application-podinfo created
          name: example-application-podinfo
          namespace: default
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          hookType: ""
          kind: Deployment
          message: deployment.apps/example-application-podinfo created
          name: example-application-podinfo
          namespace: default
          status: Synced
          syncPhase: Sync
          version: v1
        revision: b99bf8c252d47db1cccfb6546aec650679645e61
        source:
          chart: ""
          path: charts/podinfo
          ref: ""
          repoURL: https://github.com/stefanprodan/podinfo/
          targetRevision: HEAD
    resources:
    - group: ""
      health:
        message: ""
        status: Healthy
      hook: false
      kind: Service
      name: example-application-podinfo
      namespace: default
      requiresPruning: false
      status: Synced
      syncWave: 0
      version: v1
    - group: apps
      health:
        message: ""
        status: Healthy
      hook: false
      kind: Deployment
      name: example-application-podinfo
      namespace: default
      requiresPruning: false
      status: Synced
      syncWave: 0
      version: v1
    sourceType: Helm
    summary:
      images:
      - ghcr.io/stefanprodan/podinfo:6.7.1
    sync:
      comparedTo:
        destination:
          name: ""
          namespace: default
          server: https://kubernetes.default.svc
        source:
          chart: ""
          path: charts/podinfo
          ref: ""
          repoURL: https://github.com/stefanprodan/podinfo/
          targetRevision: HEAD
      revision: b99bf8c252d47db1cccfb6546aec650679645e61
      status: Synced
  conditions:
  - lastTransitionTime: "2025-02-13T05:36:16Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-02-13T05:35:15Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/applications/comp.go [hunk 1]
```diff
@@ -29,3 +31,80 @@ func IsApplicationUpToDate(cr *v1alpha1.ApplicationParameters, remote *argocdv1a
...
+// │ "Healthy"        │     *         │ Failed     │ Unavailable  │ Op Failed │
+// │ "Degraded"       │     *         │     *      │ Unavailable  │ Unhealthy │
+// │ "Progressing"    │     *         │     *      │ Unavailable  │ Not Ready │
+// │ Unknown          │     *         │     *      │ Unavailable  │ Bad State │
+// └──────────────────┴───────────────┴────────────┴──────────────┴───────────┘
+//
+// Notes:
+// - Empty status ("") indicates status not yet propagated
+// - Sync status is tracked but does not affect Ready state
+func GetApplicationCondition(status *v1alpha1.ArgoApplicationStatus) xpv1.Condition {
```
Comment (MisterMX) [inline pkg/controller/applications/comp.go:52]: This feels kind of overcomplex imho. And we should only propagate the plain external status at best without too much interpretation.

Since we are already writing the status information into `status.atProvider` it should be enough to just set the condition to `Unvailable`, `Creating` or `Available` depending on the state without generating or joining error messages.

If the current status does not expose enough information we should add another property to `status.atProvider`.

**Review by MisterMX — CHANGES_REQUESTED** [review]

File: pkg/controller/applications/comp.go (hunk 1 above)
Comment (MisterMX) [reply pkg/controller/applications/comp.go:52]: Its less about the matrix and more about the custom condition messages. We should keep the controller logic simple. I think part of that additional status information is already being done in https://github.com/crossplane-contrib/provider-argocd/pull/247

Comment (jwitko) [reply pkg/controller/applications/comp.go]: > Its less about the matrix and more about the custom condition messages. We should keep the controller logic simple. I think part of that additional status information is already being done in #247

@MisterMX please see updated commit with all custom messaging removed.

File: pkg/controller/applications/comp.go [hunk 2]
```diff
@@ -29,3 +30,28 @@ func IsApplicationUpToDate(cr *v1alpha1.ApplicationParameters, remote *argocdv1a
 
 	return cmp.Equal(*cluster, remote.Spec, opts...) && maps.Equal(cr.Annotations, remote.Annotations) && slices.Equal(cr.Finalizers, remote.Finalizers)
 }
+
+// GetApplicationCondition evaluates the application status and returns appropriate Crossplane ready state
+func GetApplicationCondition(status *v1alpha1.ArgoApplicationStatus) xpv1.Condition {
```
Comment (MisterMX) [inline pkg/controller/applications/comp.go:35]: Nit: We don't need this to be exported.

```suggestion
// getApplicationCondition evaluates the application status and returns appropriate Crossplane ready state
func getApplicationCondition(status *v1alpha1.ArgoApplicationStatus) xpv1.Condition {
```

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much @jwitko!
